// CI/CD learning stages — each shrine has a metricKey for live analytics
export const STAGES = [
  {
    id: 'commit',
    title: 'Commit Shrine',
    subtitle: 'コードを奉納する',
    position: [-4, 0, 2],
    icon: '📜',
    body: 'Commits are snapshots of your code. Every push to the main branch can trigger the pipeline. Path filters (e.g. only index.html) keep deploys intentional and save workflow minutes.',
    metric: 'Commits today',
    metricKey: 'commitsToday',
  },
  {
    id: 'build',
    title: 'Build Tower',
    subtitle: '構築の塔',
    position: [-1.5, 0, 3.5],
    icon: '🗼',
    body: 'The build step compiles your app (e.g. Vite build). Artifacts are uploaded so the next job can deploy them. No build, no deploy — quality starts here.',
    metric: 'Build time',
    metricKey: 'buildTime',
  },
  {
    id: 'test',
    title: 'Test Dojo',
    subtitle: '検証の道場',
    position: [1.5, 0, 3.5],
    icon: '⚔️',
    body: 'Validation and tests run before deploy: HTML checks, link checks, Lighthouse CI. If anything fails, the pipeline stops. Only green builds reach production.',
    metric: 'Tests passed',
    metricKey: 'testsPassed',
  },
  {
    id: 'deploy',
    title: 'Deploy Gate',
    subtitle: '本番への門',
    position: [4, 0, 2],
    icon: '🚪',
    body: 'Deploy pushes the built site to GitHub Pages (or another host). Each run writes metadata (version.json) so the live site shows "Last deployed" and commit SHA.',
    metric: 'Last deploy',
    metricKey: 'lastDeploy',
  },
  {
    id: 'monitor',
    title: 'Analytics Shrine',
    subtitle: '知識の社',
    position: [0, 0, -3],
    icon: '📊',
    body: 'Monitor your pipeline: workflow runs, success rate, and performance over time. Use the Hub to see real-time metrics and progress through the stages.',
    metric: 'Pipeline health',
    metricKey: 'pipelineHealth',
  },
]
